### PR TITLE
search product name regardless of letter case to improve user experience

### PR DESCRIPTION
**Pull request by Atlas7**
Benefits:
- searching for "base" or "Base" or "bAse" etc, will display the product row for "Baseball".
- improve user experience.
- very simple change - just a one-liner.

What has changed:
- add `toLowerCase()` during the search bar comparison part.

### CODE REVIEW

**Comment by code0wl** [comment]
Hi Atlas, 

Thanks for the PR. Can you update this PR so I can merge? :)

**Comment by Atlas7** [comment]
Hey @code0wl, I notice that all the `.jsx` components have recently been renamed to `.js` - what is the reason behind this? (I initially thought that by naming the file extension `.jsx` it gives user / interpreter a clue that the file is in React JSX syntax).

Some references on this debate:
- http://stackoverflow.com/questions/27887678/react-js-what-extension-to-use-jsx-or-just-js
- https://github.com/kriasoft/react-starter-kit/issues/52

Thanks for creating this repos by the way it has helped me learning some good practice design patterns!

**Comment by Atlas7** [comment]
Just did a `git pull` and `git rebase` and `git push` to this new feature branch. (i.e. new feature now build on top of the most up-to-date master). Hope this is ok!

(would also be grateful if you could shed some light on why changing all the `.jsx` to `.js` - to fulfil my curiosity :-)

**Comment by code0wl** [comment]
@Atlas7 The reasoning behind the renaming is that webpack is handling the resolves for JSX and JS. Not sure which editors need the extension for it to render as JSX. Using Webstorm and Atom at the moment. Both are not complaining. I'll see if more people are having this issue. If so, i'll revert to JSX.

Thanks for your PR :)))). Highly appreciated

**Comment by Atlas7** [comment]
Excellent thank you for the merge! (and keep up the great work! :)

**Pull request merged**
